title: Guangzhao Yang
url: https://ruixin.com

# Owner/author information
owner:
  name: Guangzhao Yang
  avatar: https://yangguangzhao-hnu.github.io/ygz-small.png
 # bio:
  email: yangguangzhao@139.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  github: yangguangzhao-hnu
 
# Links to include in top navigation
# For external links add external: true
links:
  - title: About Me
    url: /
  - title: Resume
    url: /file/CV-HanlinCAI.pdf
  - title: Publications
    url: /publications/
  - title: Awards
    url: /awards/
  - title: Fundings
    url: /fundings/
  - title: Hobbies
    url: /hobbies/
  - title: Blogs
    url: /blogs/

timezone: China/Beijing
future: true
highlighter: rouge
# markdown: kramdown
# markdown: redcarpet
# pygments: true


# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  # coderay:
  #   coderay_line_numbers:
  #   coderay_line_numbers_start: 1
  #   coderay_tab_width: 4
  #   coderay_bold_every: 10
  #   coderay_css: class


# disqus settings:
disqus:
  shortname: ygz

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "minimal-mistakes.sublime-project", "minimal-mistakes.sublime-workspace"]

# Latest update in 2023/09/24 by Guangzhao Yang.